// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"go-ecommerce/internal/api/handler"
	"go-ecommerce/internal/config"
	"go-ecommerce/internal/repository"
	"go-ecommerce/internal/service"
)

// Injectors from wire.go:

func InitializeProductHandler() *handler.ProductHandler {
	db := config.GetDB()
	productRepository := repository.NewProductRepository(db)
	productService := service.NewProductService(productRepository)
	productHandler := handler.NewProductHandler(productService)
	return productHandler
}

func InitializeAuthHandler() *handler.AuthHandler {
	db := config.GetDB()
	userRepository := repository.NewUserRepository(db)
	authService := service.NewAuthService(userRepository)
	authHandler := handler.NewAuthHandler(authService)
	return authHandler
}

func InitializeOrderHandler() *handler.OrderHandler {
	db := config.GetDB()
	orderRepository := repository.NewOrderRepository(db)
	orderService := service.NewOrderService(orderRepository)
	orderHandler := handler.NewOrderHandler(orderService)
	return orderHandler
}
